import asyncio
from adapters.autogen_adapter import AutoGenAdapter


class WorkflowRunner:
    def __init__(self, settings, ws_manager, task_manager):
        self.settings = settings
        self.ws = ws_manager
        self.task_manager = task_manager
        self.adapter = AutoGenAdapter(settings, ws_manager)

    async def run(self, ctx):
        task_id = ctx['taskId']
        user_request = ctx['payload'].get('userRequest', '')
        await self.ws.emit(task_id, {
            'type': 'task.status',
            'taskId': task_id,
            'payload': {'status': 'running'}
        })

        for agent in ['PlannerAgent', 'CodebaseAgent', 'DeveloperAgent', 'ReviewerAgent']:
            await self.ws.emit(task_id, {
                'type': 'agent.status',
                'taskId': task_id,
                'payload': {'agent': agent, 'status': 'running'}
            })
            result = await self.adapter.run_agent(task_id, agent, user_request, ctx)
            await self.ws.emit(task_id, {
                'type': 'agent.message',
                'taskId': task_id,
                'payload': {'agent': agent, 'content': result.get('content', '')}
            })
            await self.ws.emit(task_id, {
                'type': 'agent.status',
                'taskId': task_id,
                'payload': {'agent': agent, 'status': 'done'}
            })
            await asyncio.sleep(0.2)

        patch_text = """diff --git a/README.md b/README.md
--- a/README.md
+++ b/README.md
@@ -1 +1,3 @@
 # Demo
+
+Generated by AutoGen Code Agent skeleton.
"""
        patch = self.task_manager.save_patch(task_id, patch_text)
        await self.ws.emit(task_id, {'type': 'patch.proposed', 'taskId': task_id, 'payload': patch})
        await self.ws.emit(task_id, {
            'type': 'approval.required',
            'taskId': task_id,
            'payload': {'approvalType': 'patch', 'patchId': patch['patchId']}
        })
        await self.ws.emit(task_id, {
            'type': 'task.status',
            'taskId': task_id,
            'payload': {'status': 'waiting_patch_approval'}
        })
